### ISSUE TITLE
Expected an indented block

### ISSUE THREAD

**Issue by ahmedatawfik** [bgrolleman/authorizedkeys_ad#3]
whenever running ssh_ad_keys.py, it throws any IndentationError: expected an indented block.

**Comment by bgrolleman** [comment]
I'm surprised this wasn't reported earlier. Maybe I fixed it in place and forgot to make a commit. Thanks for letting me know. As I had the code open also made sure it works on python3.

**Comment by ahmedatawfik** [comment]
Thanks a lot.

Kind Regards,

Ahmad Amr
